build:
  @just docs
  @just playground-release
  zola build

deploy:
  git fetch
  git checkout deploy
  git reset --hard origin/deploy
  git rebase origin/main
  @just submodules
  @just build
  git rev-parse origin/main >> deployed.txt
  git add deployed.txt
  git add -f public
  git commit --amend --no-edit
  git push -f origin deploy

docs:
  cargo run -p convert-koto-docs

docs-watch:
  cargo watch -w ../modules/koto/docs -w tools/convert-koto-docs -x "run -p convert-koto-docs"

playground:
  cd playground && trunk build

playground-release:
  cd playground && trunk build --release

playground-serve:
  cd playground && trunk serve --open

playground-serve-release:
  cd playground && trunk serve --release --open

serve:
  @just docs
  @just playground
  zola serve --open --fast

serve-release:
  @just docs
  @just playground-release
  zola serve --open --fast

submodules:
  git submodule update --init --recursive

test:
  cargo watch -x test

worker:
  wrangler dev playground/gist-worker/index.js

worker-setup:
  pnpm install --dir playground/gist-worker

worker-publish:
  wrangler publish playground/gist-worker/index.js
