name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - uses: jetli/trunk-action@v0.4.0
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.34.0,zola@0.21.0

      - name: Generate Docs
        run: just docs
      - name: Build Playground
        run: just playground
      - name: Test Playground
        run: just test
      - name: Build Website
        run: just build-debug
