name: Publish

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - uses: jetli/trunk-action@v0.4.0
        with:
          version: 'v0.18.7'
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.34.0,zola@0.19.2

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Deploy
        run: just deploy
